### ISSUE TITLE
Manage "Remember me" functionality

### ISSUE THREAD

**Issue by chinzou** [openemp/openemp-api-user#10]
**Feature Description**
Allow users to chose the "Remember Me" option that keeps them authenticated for a longer period of time.
**Proposed Implementation**
allow for a user to pass an additional attribute when **authenticating** that generates a JWT with a longer expiration time.

**Additional context**
a suggested lifetime for JWT with "Remember Me" is 7 days.

**Comment by DjihadBengati** [comment]
Could do it ;)
