### ISSUE TITLE
Preflighted requests

### ISSUE THREAD

**Issue by honohunter** [openemp/openemp-api-user#15]
**Describe the bug**
Access to XMLHttpRequest at 'http://localhost:8081/api/v1/users/authenticate' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status

**To Reproduce**
send a POST request with 'content-type': 'application/json'  require to send OPTION request to determine if the actual request is safe to send.

**Expected behavior**
handle OPTION requests
**Additional context**
please check this article 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

**Comment by DjihadBengati** [comment]
I will take a look at this :)
