### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by splimter** [openemp/openemp-api-user#18]
**Describe the bug**
When i try to register a user
Am having this error **JWT Token does not begin with Bearer String**

**To Reproduce**
Send **POST** req to **api/v1/users**

**Expected behavior**
Should not ask for JWT

@chinzou

**Comment by honohunter** [comment]
@splimter 
It seems there is no issue 

**Request**
`
POST http://localhost:8081/api/v1/users HTTP/1.1
content-type: application/json

{
    "username": "user",
    "password": "user",
    "email": "user@user.me",
    "type": "ADMIN"
}
`
**Response**

`
HTTP/1.1 200 
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Thu, 02 Jul 2020 20:53:47 GMT
Connection: close

{
  "id": 3,
  "uuid": "3321037d-31f7-4571-8b4e-8b6f730d323e",
  "createdAt": "2020-07-02T20:53:47.435+0000",
  "updatedAt": "2020-07-02T20:53:47.435+0000",
  "retired": false,
  "username": "user",
  "email": "user@user.me",
  "active": null,
  "profiles": [],
  "type": "ADMIN",
  "attributes": []
}
`

**Comment by splimter** [comment]
@honohunter sir can you fork the [notification ](https://github.com/openemp/openemp-api-notification) and a test
